services: 
  nextjs: 
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    networks:
      - app-network
    environment: 
      - NODE_ENV=production
      - PORT=3000
    command: ["node", "server.js"]


networks: 
  app-network: 
    external: true